- name: Install all updates and reboot as many times as needed
  hosts: windows
  tasks:
    - name: Install updates
      ansible.windows.win_updates:
          category_names: '*'
          reboot: true